apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-gender-prediction-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fastapi-gender-prediction
  template:
    metadata:
      labels:
        app: fastapi-gender-prediction
    spec:
      containers:
      - name: fastapi-gender-prediction-container
        image: naji0630/fastapi-gender-prediction:latest
        ports:
        - containerPort: 8000
